#Build Environment

install.packages('raster')
install.packages('rgdal')
install.packages('rgeos')
install.packages('sf')
install.packages('mapview')
install.packages('RColorBrewer')
install.packages('dplyr')
install.packages('spdplyr')
install.packages('tidyverse')
install.packages('ggsn')
install.packages('classInt')
install.packages('rasterVis')
install.packages('ggplot2')
install.packages('randomForest')
install.packages('prism')
install.packages('trend')
install.packages('changepoint')
install.packages('rnoaa')
install.packages('npreg')
